spring.application.name=ExamenFinal

springdoc.swagger-ui.path=/swagger-ui.html

# Configuración con la base de datos de Render de la imagen
spring.datasource.url=jdbc:postgresql://dpg-d8qsnmeq1p3s73814120-a.oregon-postgres.render.com:5432/emergentes_tabla
spring.datasource.username=emergentes_tabla_user
spring.datasource.password=ATGBIB9FgsmTg9QNTQDAMobvUbMRtfNh
spring.datasource.driver-class-name=org.postgresql.Driver

server.forward-headers-strategy=framework
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect